version: '3.8'

services:
  app:
    image: lakishadavid/cgg_image:latest
    container_name: cgg_container
    restart: unless-stopped
    stdin_open: true  # equivalent to -i
    tty: true         # equivalent to -t
    working_dir: /home/ubuntu

